apiVersion: v1
kind: Config
preferences: {}
current-context: "dev"

clusters:
- cluster:
    certificate-authority-data: '{{config "k8s.cluster.ca" }}'
    server: '{{config "k8s.cluster.apiserver" }}'
  name: k8s-dev

contexts:
- context:
    cluster: k8s-dev
    user: '{{.user.Username}}'
  name: dev

users:
- name: '{{.user.Username}}'
  user:
    as-user-extra: {}
    auth-provider:
      config:
        apiserver-id: '{{config "k8s.oauth.serverapp" }}'
        name: azure
        client-id: '{{config "k8s.oauth.clientapp" }}'
        environment: AzurePublicCloud
        tenant-id: '{{config "k8s.oauth.tenant" }}'
